In [4]:
import numpy as np

In [9]:
a = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [8]:
b = np.array([0,1,2])
b

array([0, 1, 2])

In [22]:
mask = np.random.choice(5,3,replace=False)
mask

array([1, 0, 3])

In [23]:
a[mask]

array([[ 4,  5,  6],
       [ 1,  2,  3],
       [10, 11, 12]])