In [2]:
import numpy as np

In [3]:
a = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [4]:
b = np.array([0,1,2])
b

array([0, 1, 2])

In [5]:
mask = np.random.choice(5,3,replace=False)
mask

array([3, 4, 2])

In [6]:
np.max(a, axis=1)

array([ 3,  6,  9, 12])

In [7]:
np.exp(2) / np.exp(b)

array([7.3890561 , 2.71828183, 1.        ])

In [27]:
def softmax_loss_vectorized(W, X, y, reg):
    loss = 0.0
    dW = np.zeros_like(W)

    num_train = X.shape[0]
    num_class = W.shape[1]
    scores = X.dot(W)
    scores -= np.max(scores, axis=1).reshape(num_train, 1)
    softmax = np.exp(scores) / np.sum(np.exp(scores), axis=1).reshape(num_train, 1)

    loss = np.sum(-np.log(softmax[np.arange(num_train), y]))
    loss += reg * np.sum(W**2)

    softmax[np.arange(num_train), y] -= 1
    dW = X.T.dot(softmax)
    dW += 2 * reg * W

    return loss, dW

X = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
y = np.array([0,1,0,1])
W = np.random.randn(3,2) * 0.0001
W

array([[-7.85465695e-05, -1.22102907e-05],
       [-5.21855911e-05,  4.17231255e-05],
       [ 5.42064084e-05, -5.40888303e-05]])

In [28]:
scores = X.dot(W)
scores


array([[-2.02985264e-05, -9.10305304e-05],
       [-2.49875783e-04, -1.64758517e-04],
       [-4.79453039e-04, -2.38486503e-04],
       [-7.09030296e-04, -3.12214489e-04]])

In [29]:
num_train = X.shape[0]
num_class = W.shape[1]

In [30]:
scores -= np.max(scores, axis=1).reshape(num_train, 1)
scores

array([[ 0.00000000e+00, -7.07320041e-05],
       [-8.51172662e-05,  0.00000000e+00],
       [-2.40966536e-04,  0.00000000e+00],
       [-3.96815807e-04,  0.00000000e+00]])

In [35]:
softmax = np.exp(scores) / np.sum(np.exp(scores), axis=1).reshape(num_train, 1)
softmax

array([[0.50001768, 0.49998232],
       [0.49997872, 0.50002128],
       [0.49993976, 0.50006024],
       [0.4999008 , 0.5000992 ]])

In [37]:
loss = np.sum(-np.log(softmax[np.arange(num_train), y]))
loss

2.7724329014415066

In [39]:
softmax[np.arange(num_train), y] -= 1
softmax

array([[-0.49998232,  0.49998232],
       [ 0.49997872, -0.49997872],
       [-0.50006024,  0.50006024],
       [ 0.4999008 , -0.4999008 ]])