In [24]:
import numpy as np

In [25]:
a = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [26]:
b = np.array([0,1,2])
b

array([0, 1, 2])

In [27]:
mask = np.random.choice(5,3,replace=False)
mask

array([0, 4, 3])

In [31]:
np.max(a, axis=1)

array([ 3,  6,  9, 12])

In [37]:
np.exp(2) / np.exp(b)

array([7.3890561 , 2.71828183, 1.        ])