In [16]:
import numpy as np

a = np.array([[[1,2,3],[4,5,6]]])
a

array([[[1, 2, 3],
        [4, 5, 6]]])

In [2]:
b = np.pad(a, 2, 'constant', constant_values=0)
b

array([[0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 2, 3, 0, 0],
       [0, 0, 4, 5, 6, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0]])

In [3]:
b[1+1:5,2:2+3]

array([[1, 2, 3],
       [4, 5, 6],
       [0, 0, 0]])

In [4]:
c = np.zeros((2,3))
c

array([[0., 0., 0.],
       [0., 0., 0.]])

In [5]:
d = np.array([1,2,3,4,5,6])
d

array([1, 2, 3, 4, 5, 6])

In [15]:
e = np.pad(a, ((1,),(3,)), 'constant', constant_values=0)
e

array([[0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 2, 3, 0, 0, 0],
       [0, 0, 0, 4, 5, 6, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [7]:
mask = a == 5
b = a[:1,1:]
b

array([[2, 3]])

In [41]:
b = b * (b == 3)
b

array([[0, 3]])

In [45]:
np.unravel_index(np.argmax(a, axis=None), a.shape)

(1, 2)

In [17]:
b = np.mean(a, keepdims=True)
c = np.mean(a)
b

array([[[3.5]]])